language: rust

rust:
  - stable
  - beta
  - nightly

sudo: required

script:
  - cargo test
  - rustdoc --test README.md -L target
  - cargo doc --no-deps || echo "skipping cargo doc"

notifications:
  email:
    on_success: never

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - libiberty-dev
